//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAO_Report
    {
        public int ReportID { get; set; }
        public string Group { get; set; }
        public string StakeNo { get; set; }
        public string District { get; set; }
        public string Location { get; set; }
        public string Warehouse { get; set; }
        public string Bin { get; set; }
        public string FirstFoundSCODE { get; set; }
        public string Description { get; set; }
        public int FirstFoundQTY { get; set; }
        public int ANAO_ID { get; set; }
    
        public virtual ANAO ANAO { get; set; }
    }
}
