//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARM_Evidences
    {
        public int fId { get; set; }
        public byte[] fData { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<int> NIIN_Id { get; set; }
    
        public virtual CARM_NIINs CARM_NIINs { get; set; }
    }
}
