//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARMEntities : DbContext
    {
        public CARMEntities()
            : base("name=CARMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ANAO> ANAOs { get; set; }
        public virtual DbSet<ANAO_ManualAdjustment> ANAO_ManualAdjustment { get; set; }
        public virtual DbSet<ANAO_Report> ANAO_Report { get; set; }
        public virtual DbSet<ANAO_Summary> ANAO_Summary { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BPT_Schedule> BPT_Schedule { get; set; }
        public virtual DbSet<CARM_CARS> CARM_CARS { get; set; }
        public virtual DbSet<CARM_Evidences> CARM_Evidences { get; set; }
        public virtual DbSet<CARM_Fishbone> CARM_Fishbone { get; set; }
        public virtual DbSet<CARM_NIINs> CARM_NIINs { get; set; }
        public virtual DbSet<CARM_Reports> CARM_Reports { get; set; }
        public virtual DbSet<CARM_Schedule> CARM_Schedule { get; set; }
        public virtual DbSet<CARM_Stocktake> CARM_Stocktake { get; set; }
        public virtual DbSet<Custodian> Custodians { get; set; }
        public virtual DbSet<Mined> Mineds { get; set; }
        public virtual DbSet<SCA> SCAs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaskActivity> TaskActivities { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
