//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARM_Stocktake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARM_Stocktake()
        {
            this.CARM_NIINs = new HashSet<CARM_NIINs>();
        }
    
        public int ID { get; set; }
        public string Stake_Number { get; set; }
        public int CARM_ScheduleID { get; set; }
        public int CARM_ReportID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARM_NIINs> CARM_NIINs { get; set; }
        public virtual CARM_Reports CARM_Reports { get; set; }
    }
}
