//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARM_Reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARM_Reports()
        {
            this.CARM_Stocktake = new HashSet<CARM_Stocktake>();
        }
    
        public int ID { get; set; }
        public int Schedule_ID { get; set; }
        public Nullable<System.DateTime> dateOfCompliance { get; set; }
        public string personInterviewed { get; set; }
        public string unitName { get; set; }
        public string details { get; set; }
        public string testDetails { get; set; }
        public string findings { get; set; }
        public string actionOwner { get; set; }
        public string actionsRequired { get; set; }
        public string category { get; set; }
        public string rootAnalysis { get; set; }
        public string rootAnalysisSub { get; set; }
        public string remediated { get; set; }
        public string missingSample { get; set; }
        public string actionRequired { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> NIINCounted { get; set; }
        public Nullable<double> errorByVolume { get; set; }
        public Nullable<double> errorByValue { get; set; }
        public Nullable<System.DateTime> auditFinishDate { get; set; }
        public string warehouse { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARM_Stocktake> CARM_Stocktake { get; set; }
    }
}
