//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARM_CARS
    {
        public int ID { get; set; }
        public string Action { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public int NIIN_ID { get; set; }
        public string PreviousSchedule { get; set; }
        public string Conclusion { get; set; }
        public string Signature { get; set; }
    
        public virtual CARM_NIINs CARM_NIINs { get; set; }
    }
}
