//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custodian
    {
        public string CUSTODIAN_ID { get; set; }
        public string CUSTODIAN_TYPE { get; set; }
        public string DSTRCT_CODE { get; set; }
        public string EMPLOYEE_ID { get; set; }
        public string SUPPLY_CUST_ID { get; set; }
        public string WHOUSE_ID { get; set; }
    
        public virtual SCA SCA { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
