//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCA()
        {
            this.Custodians = new HashSet<Custodian>();
        }
    
        public string SUPPLY_CUST_ID { get; set; }
        public string SUPP_CUST_STATUS { get; set; }
        public string SC_ACCOUNT_TYPE { get; set; }
        public string LOCATION { get; set; }
        public string SUPPORTING_DSTRCT { get; set; }
        public string FAR_DISTRICT { get; set; }
        public Nullable<double> DSTRCT_LAT { get; set; }
        public Nullable<double> DSTRCT_LON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custodian> Custodians { get; set; }
    }
}
