//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskActivity
    {
        public string BIN_CODE { get; set; }
        public string CUSTODIAN_ID { get; set; }
        public string DSTRCT_CODE { get; set; }
        public string STAKE_NUMBER { get; set; }
        public string STOCK_CODE { get; set; }
        public Nullable<double> ITEM_PRICE { get; set; }
        public int COUNT_QTY { get; set; }
        public string STAKE_METHOD { get; set; }
        public string STAKE_TYPE { get; set; }
    }
}
