//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Warehouse()
        {
            this.Custodians = new HashSet<Custodian>();
        }
    
        public string DSTRCT_CODE { get; set; }
        public string DSTRCT_NAME { get; set; }
        public string DSTRCT_SUBURB { get; set; }
        public string DSTRCT_STATE { get; set; }
        public string WHOUSE_ID { get; set; }
        public double DSTRCT_LAT { get; set; }
        public double DSTRCT_LON { get; set; }
        public Nullable<double> ErrorByValue { get; set; }
        public Nullable<double> ErrorByVolume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Custodian> Custodians { get; set; }
    }
}
